# pip install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: Foundry
repo_name: foundry
repo_url: https://github.com/slackhq/foundry
site_description: "Gradle and IntelliJ build tooling used in Slack's Android projects"
site_author: Slack
remote_branch: gh-pages

copyright: 'Copyright &copy; 2024 Slack Technologies, LLC'

theme:
  name: 'material'
  favicon: images/slack_logo_small.png
  logo: images/slack_logo.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Lato'
    code: 'Fira Code'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

nav:
  - 'Overview': index.md
  - 'Platforms':
    - 'Gradle':
      - 'Architecture': platforms/gradle/architecture.md
      - 'Dependency Rake': platforms/gradle/dependency-rake.md
      - 'Bootstrap': platforms/gradle/bootstrap.md
      - 'DSL': platforms/gradle/dsl.md
      - 'Utilities': platforms/gradle/utilities.md
      # TODO
    #  - 'Configuration': platforms/gradle/configuration.md
    #  - 'Lint': platforms/gradle/lint.md
    #  - 'Testing': platforms/gradle/testing.md
    #  - 'Skippy': platforms/gradle/skippy.md
    #  - 'Properties': platforms/gradle/properties.md
    #  - 'Mod Score': platforms/gradle/mod-score.md
    #  - 'Formatters & Analysis': platforms/gradle/formatters-and-analysis.md
    #  - 'Thermals Logging': platforms/gradle/thermals-logging.md
  - 'Tools':
      - 'CLI': tools/cli.md
      # TODO
    #  - 'Skippy': tools/skippy.md
  - 'Discussions ⏏': https://github.com/slackhq/foundry/discussions
  - 'Change Log': changelog.md
  - 'API': api/0.x/
  - 'Contributing': contributing.md
  - 'CoC': code-of-conduct.md