#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\n[post-merge] This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook.\n"; exit 2; }
git lfs post-merge "$@"
