name: Renovate

on:
  schedule:
    - cron: "0 8 * * *" # 8am daily
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.SLACKHQ_MBR_GITHUB_TOKEN }}
