name: Renovate

on:
  schedule:
    - cron: "0 8 * * *" # 8am daily
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.17
        with:
          configurationFile: renovate.json
          renovate-image: renovate/renovate
          renovate-version: full
          token: ${{ secrets.SLACKHQ_MBR_GITHUB_TOKEN }}
        env:
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["tools/scripts/update-binaries\\.sh"]'
          RENOVATE_REPOSITORIES: '["slackhq/foundry"]'
